[package]
name = "just-os"
version = "0.1.0"
edition = "2021"
authors = ["Piotr Merski <merskip@gmail.com>"]

[dependencies]
bootloader = "0.9.23"
volatile = "0.2.6"

[package.metadata.bootimage]
run-command = ["qemu-system-x86_64", "-drive", "format=raw,file={}", "-gdb", "tcp::1234", "-S"]
