[package]
name = "just-os"
version = "0.1.0"
edition = "2021"
authors = ["Piotr Merski <merskip@gmail.com>"]

[dependencies]
bootloader = "0.9.23"
volatile = "0.2.6"
spin = "0.9.4"
x86_64 = "0.14.10"

[package.metadata.bootimage]
run-command = ["qemu-system-x86_64", "-drive", "format=raw,file={}", "-gdb", "tcp::1234", "-S"]

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]